apiVersion: apps/v1
kind: Deployment
metadata:
  name: tapiriik-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tapiriik-redis
  template:
    metadata:
      labels:
        app: tapiriik-redis
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: tapiriik-redis
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          name: tapiriik-redis
---
apiVersion: v1
kind: Service
metadata:
  name: tapiriik-redis
spec:
  ports:
  - port: 6379
  selector:
    app: tapiriik-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tapiriik-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tapiriik-scheduler
  template:
    metadata:
      labels:
        app: tapiriik-scheduler
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: tapiriik-scheduler
        image: neilb27/tapiriik:kubernetes
        command: ["python3"]
        args: ["sync_scheduler.py"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: DEBUG
          value: "True"
        - name: RABBITMQ_BROKER_URL
          value: amqp://guest@tapiriik_rabbitmq//
        - name: MONGO_HOST
          value: mongodb://root:example@tapiriik_mongo:27017/admin
        - name: REDIS_HOST
          value: tapiriik-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tapiriik-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tapiriik-worker
  template:
    metadata:
      labels:
        app: tapiriik-worker
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: tapiriik-worker
        image: neilb27/tapiriik:kubernetes
        command: ["python3"]
        args: ["sync_worker.py"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: DEBUG
          value: "True"
        - name: RABBITMQ_BROKER_URL
          value: amqp://guest@tapiriik_rabbitmq//
        - name: MONGO_HOST
          value: mongodb://root:example@tapiriik_mongo:27017/admin
        - name: REDIS_HOST
          value: tapiriik-redis
