apiVersion: v1
kind: Secret
metadata:
  name: tapiriik-secret
type: Opaque
stringData:
  redis-host: "tapiriik-redis"
  rabbitmq-broker-url: "amqp://guest@tapiriik_rabbitmq//"
  mongo-host: "mongodb://root:example@tapiriik_mongo:27017/admin"
  runkeeper-client-id: "####"
  runkeeper-client-secret: "####"
  dropbox-app-key: "####"
  dropbox-app-secret: "####"
  dropbox-full-app-key: "####"
  dropbox-full-app-secret: "####"
  strava-client-id: "####"
  strava-client-secret: "####"
  sporttracks-client-id: "####"
  sporttracks-client-secret: "####"