name: Docker build and push, Kubernetes apply

on:
  push:
    branches:
      - action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Docker build and push
        run: |
          docker build --tag ${{ secrets.DOCKER_USERNAME }}/tapiriik:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/tapiriik:${{ github.sha }}

      - name: kubectl apply
        run: |
          sed -i''
            -e 's/WEB_ROOT/${{ secrets.WEB_ROOT }}/g'
            -e 's/ALLOWED_HOSTS/${{ secrets.ALLOWED_HOSTS }}/g'
            kubernetes-secrets.yml
          sed -i'' -e 's/tapiriik:latest/tapiriik:${{ github.sha }}/g' kubernetes.yml
          kubectl apply -f kubernetes-secrets.yml --namespace tapiriik
          kubectl apply -f kubernetes.yml --namespace tapiriik
