name: Docker build and push, Kubernetes apply

on:
  push:
    branches:
      - master
      - run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Docker build and push
        run: |
          docker build . \
            --tag ${{ secrets.DOCKER_USERNAME }}/tapiriik:${{ github.sha }} \
            --tag ${{ secrets.DOCKER_USERNAME }}/tapiriik:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/tapiriik

      - name: kubectl apply
        # NB: the secrets need to be friendly to sed, eg & should be escaped as \&
        run: |
          sed -i'' \
            -e 's#WEB_ROOT#${{ secrets.WEB_ROOT }}#g' \
            -e 's/ALLOWED_HOSTS/${{ secrets.ALLOWED_HOSTS }}/g' \
            -e 's/EMAIL_HOST_USER/${{ secrets.EMAIL_HOST_USER }}/g' \
            -e 's/EMAIL_HOST_PASSWORD/${{ secrets.EMAIL_HOST_PASSWORD }}/g' \
            -e 's/EMAIL_HOST/${{ secrets.EMAIL_HOST }}/g' \
            -e 's/EMAIL_PORT/${{ secrets.EMAIL_PORT }}/g' \
            -e 's/EMAIL_USE_TLS/${{ secrets.EMAIL_USE_TLS }}/g' \
            -e 's#REDIS_HOST#${{ secrets.REDIS_HOST }}#g' \
            -e 's#RABBITMQ_BROKER_URL#${{ secrets.RABBITMQ_BROKER_URL }}#g' \
            -e 's#MONGO_HOST#${{ secrets.MONGO_HOST }}#g' \
            -e 's#PP_WEBSCR#${{ secrets.PP_WEBSCR }}#g' \
            -e 's#PP_RECEIVER_ID#${{ secrets.PP_RECEIVER_ID }}#g' \
            -e 's#CREDENTIAL_STORAGE_PRIVATE_KEY#${{ secrets.CREDENTIAL_STORAGE_PRIVATE_KEY }}#g' \
            -e 's#CREDENTIAL_STORAGE_PUBLIC_KEY#${{ secrets.CREDENTIAL_STORAGE_PUBLIC_KEY }}#g' \
            -e 's/RUNKEEPER_CLIENT_ID/${{ secrets.RUNKEEPER_CLIENT_ID }}/g' \
            -e 's/RUNKEEPER_CLIENT_SECRET/${{ secrets.RUNKEEPER_CLIENT_SECRET }}/g' \
            -e 's/DROPBOX_APP_KEY/${{ secrets.DROPBOX_APP_KEY }}/g' \
            -e 's/DROPBOX_APP_SECRET/${{ secrets.DROPBOX_APP_SECRET }}/g' \
            -e 's/DROPBOX_FULL_APP_KEY/${{ secrets.DROPBOX_FULL_APP_KEY }}/g' \
            -e 's/DROPBOX_FULL_APP_SECRET/${{ secrets.DROPBOX_FULL_APP_SECRET }}/g' \
            -e 's/STRAVA_CLIENT_ID/${{ secrets.STRAVA_CLIENT_ID }}/g' \
            -e 's/STRAVA_CLIENT_SECRET/${{ secrets.STRAVA_CLIENT_SECRET }}/g' \
            -e 's/SPORTTRACKS_CLIENT_ID/${{ secrets.SPORTTRACKS_CLIENT_ID }}/g' \
            -e 's/SPORTTRACKS_CLIENT_SECRET/${{ secrets.SPORTTRACKS_CLIENT_SECRET }}/g' \
            -e 's/RWGPS_APIKEY/${{ secrets.RWGPS_APIKEY }}/g' \
            kubernetes-secrets.yml
          sed -i'' -e 's/tapiriik:latest/tapiriik:${{ github.sha }}/g' kubernetes.yml
          kubectl apply -f kubernetes-secrets.yml --namespace tapiriik
          kubectl apply -f kubernetes.yml --namespace tapiriik
